/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBridge } from "./IBridge";
export type { IOriginalTokenVault } from "./IOriginalTokenVault";
export type { IOriginalTokenVaultV2 } from "./IOriginalTokenVaultV2";
export type { IPeggedTokenBridge } from "./IPeggedTokenBridge";
export type { IPeggedTokenBridgeV2 } from "./IPeggedTokenBridgeV2";
export type { ISigsVerifier } from "./ISigsVerifier";
