/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageBusAddress } from "./MessageBusAddress";
export type { MessageReceiverApp } from "./MessageReceiverApp";
export type { MessageSenderApp } from "./MessageSenderApp";
