/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as utils from "./utils";
export type { utils };
export type { ICoverageDataProviderV2 } from "./ICoverageDataProviderV2";
