/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Governable__factory } from "./Governable__factory";
export { MultichainWrapper__factory } from "./MultichainWrapper__factory";
