/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface MultichainWrapperInterface extends utils.Interface {
  functions: {
    "acceptGovernance()": FunctionFragment;
    "addCaller(address)": FunctionFragment;
    "addReceiver(uint64,address)": FunctionFragment;
    "callerAt(uint256)": FunctionFragment;
    "governance()": FunctionFragment;
    "governanceIsLocked()": FunctionFragment;
    "lockGovernance()": FunctionFragment;
    "numsOfCaller()": FunctionFragment;
    "numsOfReceiver()": FunctionFragment;
    "pendingGovernance()": FunctionFragment;
    "receiverAt(uint256)": FunctionFragment;
    "removeReceiver(uint256)": FunctionFragment;
    "setPendingGovernance(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptGovernance"
      | "addCaller"
      | "addReceiver"
      | "callerAt"
      | "governance"
      | "governanceIsLocked"
      | "lockGovernance"
      | "numsOfCaller"
      | "numsOfReceiver"
      | "pendingGovernance"
      | "receiverAt"
      | "removeReceiver"
      | "setPendingGovernance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addCaller", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addReceiver",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callerAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceIsLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numsOfCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numsOfReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiverAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReceiver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPendingGovernance",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCaller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callerAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceIsLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numsOfCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numsOfReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receiverAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPendingGovernance",
    data: BytesLike
  ): Result;

  events: {
    "GovernanceLocked()": EventFragment;
    "GovernancePending(address)": EventFragment;
    "GovernanceTransferred(address,address)": EventFragment;
    "ReceiverRemoved(uint64)": EventFragment;
    "ReceiverSet(uint64,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GovernanceLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernancePending"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiverRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiverSet"): EventFragment;
}

export interface GovernanceLockedEventObject {}
export type GovernanceLockedEvent = TypedEvent<[], GovernanceLockedEventObject>;

export type GovernanceLockedEventFilter =
  TypedEventFilter<GovernanceLockedEvent>;

export interface GovernancePendingEventObject {
  pendingGovernance: string;
}
export type GovernancePendingEvent = TypedEvent<
  [string],
  GovernancePendingEventObject
>;

export type GovernancePendingEventFilter =
  TypedEventFilter<GovernancePendingEvent>;

export interface GovernanceTransferredEventObject {
  oldGovernance: string;
  newGovernance: string;
}
export type GovernanceTransferredEvent = TypedEvent<
  [string, string],
  GovernanceTransferredEventObject
>;

export type GovernanceTransferredEventFilter =
  TypedEventFilter<GovernanceTransferredEvent>;

export interface ReceiverRemovedEventObject {
  chainId: BigNumber;
}
export type ReceiverRemovedEvent = TypedEvent<
  [BigNumber],
  ReceiverRemovedEventObject
>;

export type ReceiverRemovedEventFilter = TypedEventFilter<ReceiverRemovedEvent>;

export interface ReceiverSetEventObject {
  chainId: BigNumber;
  dst: string;
}
export type ReceiverSetEvent = TypedEvent<
  [BigNumber, string],
  ReceiverSetEventObject
>;

export type ReceiverSetEventFilter = TypedEventFilter<ReceiverSetEvent>;

export interface MultichainWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultichainWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addReceiver(
      chainId: BigNumberish,
      dst: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callerAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { caller: string }>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    governanceIsLocked(overrides?: CallOverrides): Promise<[boolean]>;

    lockGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    numsOfCaller(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    numsOfReceiver(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    pendingGovernance(overrides?: CallOverrides): Promise<[string]>;

    receiverAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { chainId: BigNumber; dst: string }>;

    removeReceiver(
      receiverIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPendingGovernance(
      pendingGovernance_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptGovernance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCaller(
    _caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addReceiver(
    chainId: BigNumberish,
    dst: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callerAt(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  governance(overrides?: CallOverrides): Promise<string>;

  governanceIsLocked(overrides?: CallOverrides): Promise<boolean>;

  lockGovernance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  numsOfCaller(overrides?: CallOverrides): Promise<BigNumber>;

  numsOfReceiver(overrides?: CallOverrides): Promise<BigNumber>;

  pendingGovernance(overrides?: CallOverrides): Promise<string>;

  receiverAt(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { chainId: BigNumber; dst: string }>;

  removeReceiver(
    receiverIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPendingGovernance(
    pendingGovernance_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptGovernance(overrides?: CallOverrides): Promise<void>;

    addCaller(_caller: string, overrides?: CallOverrides): Promise<void>;

    addReceiver(
      chainId: BigNumberish,
      dst: string,
      overrides?: CallOverrides
    ): Promise<void>;

    callerAt(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    governance(overrides?: CallOverrides): Promise<string>;

    governanceIsLocked(overrides?: CallOverrides): Promise<boolean>;

    lockGovernance(overrides?: CallOverrides): Promise<void>;

    numsOfCaller(overrides?: CallOverrides): Promise<BigNumber>;

    numsOfReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    pendingGovernance(overrides?: CallOverrides): Promise<string>;

    receiverAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { chainId: BigNumber; dst: string }>;

    removeReceiver(
      receiverIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPendingGovernance(
      pendingGovernance_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GovernanceLocked()"(): GovernanceLockedEventFilter;
    GovernanceLocked(): GovernanceLockedEventFilter;

    "GovernancePending(address)"(
      pendingGovernance?: null
    ): GovernancePendingEventFilter;
    GovernancePending(pendingGovernance?: null): GovernancePendingEventFilter;

    "GovernanceTransferred(address,address)"(
      oldGovernance?: null,
      newGovernance?: null
    ): GovernanceTransferredEventFilter;
    GovernanceTransferred(
      oldGovernance?: null,
      newGovernance?: null
    ): GovernanceTransferredEventFilter;

    "ReceiverRemoved(uint64)"(chainId?: null): ReceiverRemovedEventFilter;
    ReceiverRemoved(chainId?: null): ReceiverRemovedEventFilter;

    "ReceiverSet(uint64,address)"(
      chainId?: null,
      dst?: null
    ): ReceiverSetEventFilter;
    ReceiverSet(chainId?: null, dst?: null): ReceiverSetEventFilter;
  };

  estimateGas: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addReceiver(
      chainId: BigNumberish,
      dst: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callerAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    governanceIsLocked(overrides?: CallOverrides): Promise<BigNumber>;

    lockGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    numsOfCaller(overrides?: CallOverrides): Promise<BigNumber>;

    numsOfReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    pendingGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    receiverAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeReceiver(
      receiverIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPendingGovernance(
      pendingGovernance_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addReceiver(
      chainId: BigNumberish,
      dst: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callerAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceIsLocked(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    numsOfCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numsOfReceiver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingGovernance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiverAt(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeReceiver(
      receiverIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPendingGovernance(
      pendingGovernance_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
