/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICoverageDataProviderV2,
  ICoverageDataProviderV2Interface,
} from "../../../contracts/interfaces/ICoverageDataProviderV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "string[]",
        name: "uwpNames",
        type: "string[]",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "uwpNames",
        type: "string[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ICoverageDataProviderV2__factory {
  static readonly abi = _abi;
  static createInterface(): ICoverageDataProviderV2Interface {
    return new utils.Interface(_abi) as ICoverageDataProviderV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICoverageDataProviderV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICoverageDataProviderV2;
  }
}
