/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMessageBus } from "./IMessageBus";
export type { IMessageReceiverApp } from "./IMessageReceiverApp";
